### ISSUE TITLE
Confusing  display of high amounts 

### ISSUE THREAD

**Issue by ccris02** [kelvinwelter/polkahistory#1]
There seems to be some issue with displaying higher amounts 
We don't use Mill or Kilo to refer to Million DOT or Kilo to refer to Thousand

|Address                    							            | polkahistory.com	   | sub.id			        |
|--------------------------------------------------------------------|--------------------------|-------------------------|
|12ENWcCZ6PsMPMULpYNhoevt2cVQypcR7sBEujzQJovJVdg8 | 12.72 DOT		           | 12.72 DOT                  |
|14Ns6kKbCoka3MS4Hn6b7oRw9fFejG8RH5rq5j63cWUfpPDJ  | 20.1267 Mill DOT	   | 20,126,791.4436 DOT |
|12BkPLskXyXrHhktrinLxVFkPzzvCzCyVCaqHkUEoxMwSzeq	    | 5.162 Kilo DOT	           | 5,162.7985 DOT		|

Replace
- Mill with Million also you can display it as MDOT
- Kilo with Thousand

https://wiki.polkadot.network/docs/learn-DOT

**Comment by kelvinwelter** [comment]
Hey @ccris02, thanks for opening this issue.  It's really not in the correct format.  I will fix it within the next few days.

**Comment by ccris02** [comment]
Had few questions for you:
-When are you planning to add Kusama?
-Are you planning to add other parachains?
Let me know when you do I would like to open a Tip for you.

**Comment by kelvinwelter** [comment]
Hey @ccris02

Q: When are you planning to add Kusama?
A: I have already added Kusama to the application, you can check the history of Kusama accounts by clicking the button (I'm concerned about the visibility of the Kusama Button after your comment, maybe I'll make some changes to make it more visible.) highlighted in red in the screenshot below:

![image](https://user-images.githubusercontent.com/37090245/162650214-ffbaed25-78f2-4783-9707-af8a58438042.png)

Q: Are you planning to add other parachains?
A: Well, initially Polkahistory will only have Kusama and Polkadot. However, adding other parachains is quite simple and I can add them if interested. Is there a parachain you are interested in seeing available on Polkahistory?

**Comment by ccris02** [comment]
I've seen the Kusama icon but it doesn't seem to be working, I have try multiple accounts with same result.
![image](https://user-images.githubusercontent.com/66147586/162652910-e4bf3d68-0405-47ee-b2d7-54f9a95025ae.png)

**Comment by kelvinwelter** [comment]
Hey @ccris02

It's true, the Kusama part isn't working. I will fix this bug this week, I will also add unit tests to prevent this from happening again. Thanks for sharing your problem!

**Comment by ccris02** [comment]
Hi Kelvin, how hard  would it be to get balance from single address but for all of your crypto at a certain time.
Like you can see on sub.id you can past your Polkadot address but it shows you your DOT, KSM, ACA, etc...

 https://sub.id/12ENWcCZ6PsMPMULpYNhoevt2cVQypcR7sBEujzQJovJVdg8

**Comment by kelvinwelter** [comment]
Hey @ccris02 

To search the balance on a network, the site must perform a binary search on the blockchain. To find the block closest to the timestamp desired by the user. This binary search is already time-consuming for a single network. This makes it impractical (as far as I know) to implement a feature that shows your account balance on all networks at a given timestamp.

**Comment by kelvinwelter** [comment]
Fixed on https://github.com/kelvinwelter/polkahistory/commit/be04303634922037b6ed13ad00e8d26d59722f94

**Comment by ccris02** [comment]
Yahh, I guess someone already beat me and submitted a tip. [Polkadot Tip](https://polkadot.polkassembly.io/tip/0xf9203e744024f21e639ffd0c6f5932e30658f5982141ef4f4c8611275dab0b02)

**Comment by laurogripa** [comment]
> Yahh, I guess someone already beat me and submitted a tip. [Polkadot Tip](https://polkadot.polkassembly.io/tip/0xf9203e744024f21e639ffd0c6f5932e30658f5982141ef4f4c8611275dab0b02)

Sorry, @ccris02. I had no idea you wanted to propose the tip, but Kelvin and I know each other in-person, I introduced him to DotSama and helped with some other issues in private since the beginning.

**Comment by ccris02** [comment]
@laurogripa it's all good, most important thing is that @kelvinwelter gets recognized for his work.
